stages:
  - build
  - deploy

docker-build:
  stage: build
  image: docker:cli
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_BUILDKIT: "1"
    BUILDKIT_INLINE_CACHE: "1"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --pull --cache-from $CI_REGISTRY_IMAGE:latest --build-arg NEXT_PUBLIC_SITE_URL=https://dread.lol -t $DOCKER_IMAGE_NAME .
    - docker push $DOCKER_IMAGE_NAME
    - |
      if [[ $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH ]]; then
        docker tag $DOCKER_IMAGE_NAME $CI_REGISTRY_IMAGE:latest
        docker push $CI_REGISTRY_IMAGE:latest
      fi
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile

deploy-coolify:
  stage: deploy
  image: curlimages/curl:latest
  script:
    - |
      curl -X GET "https://coolify.ithildin.co/api/v1/deploy?uuid=rock48o8kccgwsw40g00g0co&force=false" \
        -H "Authorization: Bearer $COOLIFY_API_TOKEN" \
        -H "Accept: application/json" \
        -w "\nHTTP Status: %{http_code}\n" \
        -f
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      exists:
        - Dockerfile
